### PR TITLE
Write tests in Python

### LINKED ISSUE #96: When converting the same TIFF file twice, Sipi doesn't produce the same result
```
$ local/bin/sipi -format jpg test/_test_data/images/knora/Leaves8.tif test1.jpg
$ local/bin/sipi -format jpg test/_test_data/images/knora/Leaves8.tif test2.jpg
$ diff test1.jpg test2.jpg
Binary files test1.jpg and test2.jpg differ

$ local/bin/sipi -format png test/_test_data/images/knora/Leaves8.tif test1.png
$ local/bin/sipi -format png test/_test_data/images/knora/Leaves8.tif test2.png
$ diff test1.png test2.png
Binary files test1.png and test2.png differ
```

### PR DESCRIPTION
**Pull request by benjamingeer**
This adds a testing framework based on [Pytest](http://doc.pytest.org/en/latest/), replacing both the bash scripts and the Scala-based tests.

So far, there are:

* Simple tests that check that Sipi is running and can return a file.
* Image conversion tests that use [GraphicsMagick](http://www.graphicsmagick.org/) to compare image data (but not metadata)
* A test that runs the [IIIF Validator](https://github.com/IIIF/image-validator)

I used Sipi's output to create the files representing the expected test results, so I don't know if they're actually correct. We should check this in some other way.

To run the tests, you'll need Python 3.5 or above (`brew install python3` should do it), and:

```
brew install nginx
brew install libmagic
brew install graphicsmagick --with-jasper
pip3 install pytest
pip3 install requests
pip3 install psutil
pip3 install iiif_validator
```

Then in the `build` directory, you can type:

```
make check
```

Closes #96.

### CODE REVIEW

**Comment by benjamingeer** [comment]
Actually the conversion from TIFF to PNG doesn't always produce the same number of bytes.

**Comment by lrosenth** [comment]
I get the following result after running the test (and installing nginx with home-brew..)

===================================================== test session starts ======================================================
platform darwin -- Python 3.6.0, pytest-3.0.5, py-1.4.32, pluggy-0.4.0
rootdir: /Users/rosenth/ProgDev/Sipi, inifile: 
collected 13 items 

TestBasic: Sipi should start E
TestBasic: Sipi should add routes E
TestBasic: Sipi should return an unmodified JPG file containing the same bytes E
TestConversions: Sipi should convert Leaves8.tif to a JPG file containing the expected number of bytes E
TestConversions: Sipi should convert Leaves8.tif to a PNG file containing the expected number of bytes E
TestConversions: Sipi should convert Leaves8.tif to a JP2 file containing the expected bytes E
TestConversions: Sipi should convert Leaves16.tif to a JPG file containing the expected number of bytes E
TestConversions: Sipi should convert Leaves16.tif to a PNG file containing the expected bytes E
TestConversions: Sipi should convert Leaves16.tif to a JP2 file containing the expected bytes E
TestConversions: Sipi should convert LeavesC.jp2 to a JPG file containing the expected number of bytes E
TestConversions: Sipi should convert LeavesC.jp2 to a PNG file containing the expected bytes E
TestConversions: Sipi should convert LeavesR.jp2 to a JPG file containing the expected number of bytes E
TestConversions: Sipi should convert LeavesR.jp2 to a PNG file containing the expected bytes E

============================================================ ERRORS ============================================================
_________________________________________ ERROR at setup of TestBasic.test_sipi_starts _________________________________________

    @pytest.fixture(scope="session")
    def manager():
        """Returns a SipiTestManager. Automatically starts Sipi and nginx before tests are run, and stops them afterwards."""
>       manager = SipiTestManager()

test/conftest.py:37: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
test/conftest.py:55: in __init__
    sipi_config = self.config["Sipi"]
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <configparser.ConfigParser object at 0x10840a828>, key = 'Sipi'

    def __getitem__(self, key):
        if key != self.default_section and not self.has_section(key):
>           raise KeyError(key)
E           KeyError: 'Sipi'

/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/configparser.py:956: KeyError
_______________________________________ ERROR at setup of TestBasic.test_sipi_log_output _______________________________________

    @pytest.fixture(scope="session")
    def manager():
        """Returns a SipiTestManager. Automatically starts Sipi and nginx before tests are run, and stops them afterwards."""
>       manager = SipiTestManager()

test/conftest.py:37: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
test/conftest.py:55: in __init__
    sipi_config = self.config["Sipi"]
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <configparser.ConfigParser object at 0x10840a828>, key = 'Sipi'

    def __getitem__(self, key):
        if key != self.default_section and not self.has_section(key):
>           raise KeyError(key)
E           KeyError: 'Sipi'

/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/configparser.py:956: KeyError
_________________________________________ ERROR at setup of TestBasic.test_file_bytes __________________________________________

    @pytest.fixture(scope="session")
    def manager():
        """Returns a SipiTestManager. Automatically starts Sipi and nginx before tests are run, and stops them afterwards."""
>       manager = SipiTestManager()

test/conftest.py:37: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
test/conftest.py:55: in __init__
    sipi_config = self.config["Sipi"]
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <configparser.ConfigParser object at 0x10840a828>, key = 'Sipi'

    def __getitem__(self, key):
        if key != self.default_section and not self.has_section(key):
>           raise KeyError(key)
E           KeyError: 'Sipi'

/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/configparser.py:956: KeyError
______________________________________ ERROR at setup of TestConversions.test_tif8_to_jpg ______________________________________

    @pytest.fixture(scope="session")
    def manager():
        """Returns a SipiTestManager. Automatically starts Sipi and nginx before tests are run, and stops them afterwards."""
>       manager = SipiTestManager()

test/conftest.py:37: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
test/conftest.py:55: in __init__
    sipi_config = self.config["Sipi"]
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <configparser.ConfigParser object at 0x10840a828>, key = 'Sipi'

    def __getitem__(self, key):
        if key != self.default_section and not self.has_section(key):
>           raise KeyError(key)
E           KeyError: 'Sipi'

/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/configparser.py:956: KeyError
______________________________________ ERROR at setup of TestConversions.test_tif8_to_png ______________________________________

    @pytest.fixture(scope="session")
    def manager():
        """Returns a SipiTestManager. Automatically starts Sipi and nginx before tests are run, and stops them afterwards."""
>       manager = SipiTestManager()

test/conftest.py:37: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
test/conftest.py:55: in __init__
    sipi_config = self.config["Sipi"]
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <configparser.ConfigParser object at 0x10840a828>, key = 'Sipi'

    def __getitem__(self, key):
        if key != self.default_section and not self.has_section(key):
>           raise KeyError(key)
E           KeyError: 'Sipi'

/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/configparser.py:956: KeyError
______________________________________ ERROR at setup of TestConversions.test_tif8_to_jp2 ______________________________________

    @pytest.fixture(scope="session")
    def manager():
        """Returns a SipiTestManager. Automatically starts Sipi and nginx before tests are run, and stops them afterwards."""
>       manager = SipiTestManager()

test/conftest.py:37: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
test/conftest.py:55: in __init__
    sipi_config = self.config["Sipi"]
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <configparser.ConfigParser object at 0x10840a828>, key = 'Sipi'

    def __getitem__(self, key):
        if key != self.default_section and not self.has_section(key):
>           raise KeyError(key)
E           KeyError: 'Sipi'

/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/configparser.py:956: KeyError
_____________________________________ ERROR at setup of TestConversions.test_tif16_to_jpg ______________________________________

    @pytest.fixture(scope="session")
    def manager():
        """Returns a SipiTestManager. Automatically starts Sipi and nginx before tests are run, and stops them afterwards."""
>       manager = SipiTestManager()

test/conftest.py:37: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
test/conftest.py:55: in __init__
    sipi_config = self.config["Sipi"]
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <configparser.ConfigParser object at 0x10840a828>, key = 'Sipi'

    def __getitem__(self, key):
        if key != self.default_section and not self.has_section(key):
>           raise KeyError(key)
E           KeyError: 'Sipi'

/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/configparser.py:956: KeyError
_____________________________________ ERROR at setup of TestConversions.test_tif16_to_png ______________________________________

    @pytest.fixture(scope="session")
    def manager():
        """Returns a SipiTestManager. Automatically starts Sipi and nginx before tests are run, and stops them afterwards."""
>       manager = SipiTestManager()

test/conftest.py:37: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
test/conftest.py:55: in __init__
    sipi_config = self.config["Sipi"]
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <configparser.ConfigParser object at 0x10840a828>, key = 'Sipi'

    def __getitem__(self, key):
        if key != self.default_section and not self.has_section(key):
>           raise KeyError(key)
E           KeyError: 'Sipi'

/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/configparser.py:956: KeyError
_____________________________________ ERROR at setup of TestConversions.test_tif16_to_jp2 ______________________________________

    @pytest.fixture(scope="session")
    def manager():
        """Returns a SipiTestManager. Automatically starts Sipi and nginx before tests are run, and stops them afterwards."""
>       manager = SipiTestManager()

test/conftest.py:37: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
test/conftest.py:55: in __init__
    sipi_config = self.config["Sipi"]
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <configparser.ConfigParser object at 0x10840a828>, key = 'Sipi'

    def __getitem__(self, key):
        if key != self.default_section and not self.has_section(key):
>           raise KeyError(key)
E           KeyError: 'Sipi'

/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/configparser.py:956: KeyError
______________________________________ ERROR at setup of TestConversions.test_jp2c_to_jpg ______________________________________

    @pytest.fixture(scope="session")
    def manager():
        """Returns a SipiTestManager. Automatically starts Sipi and nginx before tests are run, and stops them afterwards."""
>       manager = SipiTestManager()

test/conftest.py:37: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
test/conftest.py:55: in __init__
    sipi_config = self.config["Sipi"]
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <configparser.ConfigParser object at 0x10840a828>, key = 'Sipi'

    def __getitem__(self, key):
        if key != self.default_section and not self.has_section(key):
>           raise KeyError(key)
E           KeyError: 'Sipi'

/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/configparser.py:956: KeyError
______________________________________ ERROR at setup of TestConversions.test_jp2c_to_png ______________________________________

    @pytest.fixture(scope="session")
    def manager():
        """Returns a SipiTestManager. Automatically starts Sipi and nginx before tests are run, and stops them afterwards."""
>       manager = SipiTestManager()

test/conftest.py:37: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
test/conftest.py:55: in __init__
    sipi_config = self.config["Sipi"]
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <configparser.ConfigParser object at 0x10840a828>, key = 'Sipi'

    def __getitem__(self, key):
        if key != self.default_section and not self.has_section(key):
>           raise KeyError(key)
E           KeyError: 'Sipi'

/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/configparser.py:956: KeyError
______________________________________ ERROR at setup of TestConversions.test_jp2r_to_jpg ______________________________________

    @pytest.fixture(scope="session")
    def manager():
        """Returns a SipiTestManager. Automatically starts Sipi and nginx before tests are run, and stops them afterwards."""
>       manager = SipiTestManager()

test/conftest.py:37: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
test/conftest.py:55: in __init__
    sipi_config = self.config["Sipi"]
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <configparser.ConfigParser object at 0x10840a828>, key = 'Sipi'

    def __getitem__(self, key):
        if key != self.default_section and not self.has_section(key):
>           raise KeyError(key)
E           KeyError: 'Sipi'

/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/configparser.py:956: KeyError
______________________________________ ERROR at setup of TestConversions.test_jp2r_to_png ______________________________________

    @pytest.fixture(scope="session")
    def manager():
        """Returns a SipiTestManager. Automatically starts Sipi and nginx before tests are run, and stops them afterwards."""
>       manager = SipiTestManager()

test/conftest.py:37: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
test/conftest.py:55: in __init__
    sipi_config = self.config["Sipi"]
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <configparser.ConfigParser object at 0x10840a828>, key = 'Sipi'

    def __getitem__(self, key):
        if key != self.default_section and not self.has_section(key):
>           raise KeyError(key)
E           KeyError: 'Sipi'

/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/configparser.py:956: KeyError
=================================================== 13 error in 1.82 seconds ===================================================

**Comment by benjamingeer** [comment]
Did you remember to `cd test` before running `py.test`?

Probably there should be a `make test` target in `build`.

**Comment by BiancoA** [comment]
would it be possible to integrate also https://github.com/IIIF/image-validator  tests? It could be integrated directly in Travis (see https://github.com/IIIF/image-validator#use-with-travis-ci). It should be noted anyway that to pass the tests, their test image (http://iiif.io/api/image/validator/67352ccc-d1b0-11e1-89ae-279075081939.jp2) has to be used.

**Comment by benjamingeer** [comment]
> would it be possible to integrate also https://github.com/IIIF/image-validator tests?

I'll do this ASAP. I hope to do it quickly, so I'll keep working on this branch.

**Comment by lrosenth** [comment]
@benjamingeer Yes, I did the `cd test`before running the tests! Same problem on my mac at the DHLab...

**Comment by lrosenth** [comment]
@benjamingeer 

Ben, could You comment on this:

>For some conversions (e.g. TIFF to JPG), Sipi doesn’t produce the same bytes each time if you run
>the same conversion twice. I don’t know whether this is correct or not. In those cases, the tests just
>look at the number of bytes in the file, which seems to be constant.

What are the files and commands You used? This should not happen – turing machines should be deterministic ;-)

**Comment by benjamingeer** [comment]
@lrosenth 

> Yes, I did the cd testbefore running the tests

Strange. I'm asking because your output says:

```
rootdir: /Users/rosenth/ProgDev/Sipi
```

But I only get that when I run `pytest` in the root directory of the project. When I run it in the `test` directory, I get:

```
rootdir: /Users/benjamingeer/git/Sipi/test
```

The error you're getting suggests that the config file `config.ini` is not being found. Can you pull the `python-test` branch from git and try again? I added a check to ensure that the configuration file exists, and to give a better error message if it's not found.

> What are the files and commands You used?

First, delete Sipi's `cache` directory to ensure it doesn't use caching. Then load this URL twice in a browser, and save the two files as `test1.jpg` and `test2.jpg`:

http://localhost:1024/knora/Leaves8.tif/full/full/0/default.jpg

Then:

```
$ diff test1.jpg test2.jpg
Binary files test1.jpg and test2.jpg differ
```

**Comment by lrosenth** [comment]
snoopy:test rosenth$ pwd
/Users/rosenth/ProgDev/Sipi/test
snoopy:test rosenth$ py.test
==================================================== test session starts =====================================================
platform darwin -- Python 3.6.0, pytest-3.0.5, py-1.4.32, pluggy-0.4.0
rootdir: /Users/rosenth/ProgDev/Sipi/test, inifile:
collected 13 items

TestBasic: Sipi should start E
TestBasic: Sipi should add routes E
TestBasic: Sipi should return an unmodified JPG file containing the same bytes E
TestConversions: Sipi should convert Leaves8.tif to a JPG file containing the expected number of bytes E
TestConversions: Sipi should convert Leaves8.tif to a PNG file containing the expected number of bytes E
TestConversions: Sipi should convert Leaves8.tif to a JP2 file containing the expected bytes E
TestConversions: Sipi should convert Leaves16.tif to a JPG file containing the expected number of bytes E
TestConversions: Sipi should convert Leaves16.tif to a PNG file containing the expected bytes E
TestConversions: Sipi should convert Leaves16.tif to a JP2 file containing the expected bytes E
TestConversions: Sipi should convert LeavesC.jp2 to a JPG file containing the expected number of bytes E
TestConversions: Sipi should convert LeavesC.jp2 to a PNG file containing the expected bytes E
TestConversions: Sipi should convert LeavesR.jp2 to a JPG file containing the expected number of bytes E
TestConversions: Sipi should convert LeavesR.jp2 to a PNG file containing the expected bytes E

=========================================================== ERRORS ===========================================================
________________________________________ ERROR at setup of TestBasic.test_sipi_starts ________________________________________

    @pytest.fixture(scope="session")
    def manager():
        """Returns a SipiTestManager. Automatically starts Sipi and nginx before tests are run, and stops them afterwards."""
        manager = SipiTestManager()
>       manager.start_nginx()

conftest.py:39:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <conftest.SipiTestManager object at 0x10e77ccf8>

** and many more error messages **

Am 12.01.2017 um 18:32 schrieb Benjamin Geer <notifications@github.com<mailto:notifications@github.com>>:


@lrosenth<https://github.com/lrosenth>

Yes, I did the cd testbefore running the tests

Strange. I'm asking because your output says:

rootdir: /Users/rosenth/ProgDev/Sipi


But I only get that when I run pytest in the root directory of the project. When I run it in the test directory, I get:

rootdir: /Users/benjamingeer/git/Sipi/test


The error you're getting suggests that the config file config.ini is not being found. Can you pull the python-test branch from git and try again? I added a check to ensure that the configuration file exists, and to give a better error message if it's not found.

What are the files and commands You used?

First, delete Sipi's cache directory to ensure it doesn't use caching. Then load this URL twice in a browser, and save the two files as test1.jpg and test2.jpg:

http://localhost:1024/knora/Leaves8.tif/full/full/0/default.jpg

Then:

$ diff test1.jpg test2.jpg
Binary files test1.jpg and test2.jpg differ

**Comment by benjamingeer** [comment]
> and many more error messages

What's the last error message? That will show the specific cause of the problem.

**Comment by lrosenth** [comment]
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <conftest.SipiTestManager object at 0x10608bcf8>

    def start_nginx(self):
        """Starts nginx."""
        nginx_log_dir = os.path.join(self.nginx_working_dir, "logs")

        if not os.path.exists(nginx_log_dir):
            os.makedirs(nginx_log_dir)

        nginx_args = shlex.split(self.start_nginx_command)
>       assert subprocess.run(nginx_args).returncode == 0, "nginx failed to start"
E       AssertionError: nginx failed to start
E       assert 1 == 0
E        +  where 1 = CompletedProcess(args=['nginx', '-p', '/Users/rosenth/ProgDev/Sipi/test/nginx', '-c', 'nginx.conf'], returncode=1).returncode
E        +    where CompletedProcess(args=['nginx', '-p', '/Users/rosenth/ProgDev/Sipi/test/nginx', '-c', 'nginx.conf'], returncode=1) = <function run at 0x10541b0d0>(['nginx', '-p', '/Users/rosenth/ProgDev/Sipi/test/nginx', '-c', 'nginx.conf'])
E        +      where <function run at 0x10541b0d0> = subprocess.run

conftest.py:130: AssertionError
================================================== 13 error in 2.75 seconds ==================================================
snoopy:test rosenth$ brew install nginx
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
autotrace         certbot           grafana           lmdb              notmuch           ruby-build        terraform
bind              darcs             imagemagick       macvim            openconnect       rust              udunits
blockhash         dbt               kobalt            mktorrent         pstoedit          stoken            vim
cattle            gnutls            kubernetes-cli    mongo-c-driver    rancid            synfig            zbar

Warning: nginx-1.10.2_1 already installed


Am 12.01.2017 um 18:42 schrieb Benjamin Geer <notifications@github.com<mailto:notifications@github.com>>:


and many more error messages

What's the last error message? That will show the specific cause of the problem.

**Comment by benjamingeer** [comment]
Probably nginx failed to start because it is already running. I will try to improve the test framework so this doesn't happen. In the meantime, please type this (still in the `test` directory) and try again:

```
nginx -p nginx -c nginx.conf -s stop
```

**Comment by lrosenth** [comment]
:-)

It works!! Thanks!!

snoopy:test rosenth$ py.test
==================================================== test session starts =====================================================
platform darwin -- Python 3.6.0, pytest-3.0.5, py-1.4.32, pluggy-0.4.0
rootdir: /Users/rosenth/ProgDev/Sipi/test, inifile:
collected 13 items

TestBasic: Sipi should start .
TestBasic: Sipi should add routes .
TestBasic: Sipi should return an unmodified JPG file containing the same bytes .
TestConversions: Sipi should convert Leaves8.tif to a JPG file containing the expected number of bytes .
TestConversions: Sipi should convert Leaves8.tif to a PNG file containing the expected number of bytes .
TestConversions: Sipi should convert Leaves8.tif to a JP2 file containing the expected bytes .
TestConversions: Sipi should convert Leaves16.tif to a JPG file containing the expected number of bytes .
TestConversions: Sipi should convert Leaves16.tif to a PNG file containing the expected bytes .
TestConversions: Sipi should convert Leaves16.tif to a JP2 file containing the expected bytes .
TestConversions: Sipi should convert LeavesC.jp2 to a JPG file containing the expected number of bytes .
TestConversions: Sipi should convert LeavesC.jp2 to a PNG file containing the expected bytes .
TestConversions: Sipi should convert LeavesR.jp2 to a JPG file containing the expected number of bytes .
TestConversions: Sipi should convert LeavesR.jp2 to a PNG file containing the expected bytes .

================================================= 13 passed in 19.61 seconds =================================================

Am 12.01.2017 um 18:45 schrieb Benjamin Geer <notifications@github.com<mailto:notifications@github.com>>:


nginx -p nginx -c nginx.conf -s stop

**Comment by benjamingeer** [comment]
I'm glad it worked for you. I get these errors:

```
TestConversions: Sipi should convert Leaves8.tif to a PNG file containing the expected number of bytes F
TestConversions: Sipi should convert LeavesC.jp2 to a JPG file containing the expected number of bytes F
TestConversions: Sipi should convert LeavesC.jp2 to a PNG file containing the expected bytes F
```

I'm wondering if it's just not feasible to do byte-for-byte comparisons.

**Comment by lrosenth** [comment]
@benjamingeer @BiancoA 
OK, I did find out a little about these differences. It has to to with the processing of the ICC Color profile. Since we are using the littlecms2, the ICC profile is a little different (that is, only the id-string).
How did You generate the original JPG. Also using SIPI (command line)?

**Comment by benjamingeer** [comment]
These files were already in git when I started:

https://github.com/dhlab-basel/Sipi/tree/878c1b87dea2a288fd167b7132107d5e4eb83640/test_server/images

I don't know how they were made. I generated the other files using the Sipi server.

**Comment by benjamingeer** [comment]
I opened #96 for the issue in which Sipi does the same conversion twice but produces different results.

**Comment by benjamingeer** [comment]
I added a `make check` target that runs the tests (`make test` is reserved for CMake's own testing framework).

I also added code to stop any running Sipi or nginx process before running tests. To use this, you'll need:

```
pip3 install psutil
```

**Comment by benjamingeer** [comment]
Now I'm really confused.

I added the IIIF validator test image to git. I installed the IIIF validator like this:

```
brew install libmagic
pip3 install iiif_validator
```

(By the way, I now see that `libmagic` has nothing to do with ImageMagick.)

I ran Sipi like this:

```
build/sipi -config config/sipi.test-config.lua
```

Then I ran the validator like this:

```
iiif-validate.py -s localhost:1024 -p knora -i 67352ccc-d1b0-11e1-89ae-279075081939.jp2 --version=2.0 -v
```

All the validator tests passed. But if I run Sipi like this:

```
build/sipi -config config/sipi.no-knora-test-config.lua
```

I get lots of validator failures. Is Sipi's IIIF functionality dependent on something in the Lua permission-checking scripts?

**Comment by benjamingeer** [comment]
I switched from ImageMagick to GraphicsMagick, because it's easier to install it with JPEG 2000 support.

**Comment by lrosenth** [comment]
Hi Ben, please merge!! Code is OK!

**Pull request merged**
