### PR TITLE
fix (metadata): concurrency bug in XMP library

### LINKED ISSUE #184: Sipi crashes under load when requesting many IIIF-URLs with regions
```
Jun 30 14:16:09  Sipi[65926] <Info>: GET /knora/4RwB1FEzM21-EA4X6lzfgiD.jpx/pct:38.12154696132597,28.994708994708994,18.093922651933703,8.677248677248677/pct:20/0/default.jpg: file ./images/knora/4RwB1FEzM21-EA4X6lzfgiD.jpx
Error: XMP toolkit initialization failed.
Jun 30 14:16:09  Sipi[65926] <Debug>: IIIF-Server Region:  Coordinate type: 2 | rx = 55.248619 | ry = 28.042328 | rw = 42.955803 | rh = 11.851851
Sipi Error at [/Users/tobi/gitreps/Sipi_github/src/metadata/SipiXmp.cpp: 124]: Failed to serialize XMP data!

Segmentation fault: 11
```

This happens when I request many image regions. This used to work without any problems before. Today, I built develop from scratch and now it crashes. 

```
Sipi Version 1.0 Beta (build 2017-06-30 10:57)
Sipi Source Git-Version: a82a370
```

`subdir_levels = 0`

I shared the file with you via Dropbox.

### PR DESCRIPTION
**Pull request by lrosenth**
Removed parsing and generating of XMP-header using exiv2. XMP is now just treated as blob.
Closes #184

### CODE REVIEW

**Comment by tobiasschweizer** [comment]
Ok, I reran the requests that make Sipi crash on Friday. Now on this branch, everything runs smoothly as it did the months before.

**Comment by tobiasschweizer** [comment]
@rosenth Before emerging this back to `develop`, could we provide a load test so that we can check for this kind of problem in the future?

**Comment by subotic** [comment]
what is the status of this PR. can it be merged?

**Comment by lrosenth** [comment]
Merged into fragmentarium branch

**Pull request closed without merging**
