### PR TITLE
Wip/lua number

### PR DESCRIPTION
**Pull request by tobiasschweizer**
improve error handling in Lua routes

### CODE REVIEW

**Comment by tobiasschweizer** [comment]
closes #64 #67 #60

**Comment by tobiasschweizer** [comment]
@BiancoA Lukas was ok with https://github.com/dhlab-basel/Sipi/pull/68/commits/3a1b130f09c8cee03856870b4b6d5dae88ca89d5

The other changes affect only the Lua routes. Is it ok for you I merge this back to `develop`?

**Comment by BiancoA** [comment]
@tobiasschweizer it is perfectly ok! go and merge it.

**Comment by lrosenth** [comment]
That's OK – please merge!!

**Pull request merged**
