### PR TITLE
Update external libs

### PR DESCRIPTION
**Pull request by lrosenth**
Updated all external libraries to the most recent ones, added a small bugfix to read PNG-images with invalid EXIF-data (as contributed by Loïc :-)  (try/catch around EXIV2-library call)

### CODE REVIEW

**Comment by benjamingeer** [comment]
The build works for me on my machine, but for some reason it's failing to build `libcurl` on Travis:

screen shot 2018-11-19 at 08 48 16

**Comment by benjamingeer** [comment]
Also, when I build locally, and type `make install`, I get this error:

```
Install the project...
-- Install configuration: ""
-- Installing: /Users/benjamingeer/git/Sipi/local/bin/sipi
CMake Error at cmake_install.cmake:57 (file):
  file INSTALL cannot find
  "/Users/benjamingeer/git/Sipi/local/bin/luarocks-5.3".
```

**Comment by subotic** [comment]
You could try to build inside docker (see documentation). This will provide you with the same environment as Travis is using.

**Comment by loicjaouen** [comment]
@subotic : trying to build inside docker as you recommended:
```bash
docker run --rm -v $PWD:/sipi dhlabbasel/sipi-base:18.04 /bin/sh -c "cd /sipi/build; cmake .. && make"
/.../
checking whether to enable Windows native SSL/TLS (Windows native builds only)... no
checking whether to enable Apple OS native SSL/TLS... no
configure: error:  is a bad --with-ssl prefix!
ext/curl/CMakeFiles/project_curl.dir/build.make:108: recipe for target 'ext/curl/project_curl-prefix/src/project_curl-stamp/project_curl-configure' failed
make[2]: *** [ext/curl/project_curl-prefix/src/project_curl-stamp/project_curl-configure] Error 1
CMakeFiles/Makefile2:232: recipe for target 'ext/curl/CMakeFiles/project_curl.dir/all' failed
make[1]: *** [ext/curl/CMakeFiles/project_curl.dir/all] Error 2
make: *** [all] Error 2
Makefile:140: recipe for target 'all' failed
```

**Comment by lrosenth** [comment]
We’ll go for the problem this afternoon....

Sent from my iPad

On 20 Nov 2018, at 12:55, Loïc Jaouen <notifications@github.com<mailto:notifications@github.com>> wrote:


@subotic<https://github.com/subotic> : trying to build inside docker as you recommended:

docker run --rm -v $PWD:/sipi dhlabbasel/sipi-base:18.04 /bin/sh -c "cd /sipi/build; cmake .. && make"
/.../
checking whether to enable Windows native SSL/TLS (Windows native builds only)... no
checking whether to enable Apple OS native SSL/TLS... no
configure: error:  is a bad --with-ssl prefix!
ext/curl/CMakeFiles/project_curl.dir/build.make:108: recipe for target 'ext/curl/project_curl-prefix/src/project_curl-stamp/project_curl-configure' failed
make[2]: *** [ext/curl/project_curl-prefix/src/project_curl-stamp/project_curl-configure] Error 1
CMakeFiles/Makefile2:232: recipe for target 'ext/curl/CMakeFiles/project_curl.dir/all' failed
make[1]: *** [ext/curl/CMakeFiles/project_curl.dir/all] Error 2
make: *** [all] Error 2
Makefile:140: recipe for target 'all' failed

**Comment by subotic** [comment]
I think I have found the problem. The variable `OPENSSL_ROOT_DIR`, for whatever reason, is empty under Ubuntu (Docker).

**Comment by loicjaouen** [comment]
what should it be set to?

**Comment by loicjaouen** [comment]
I couldn't make it work in server mode:

```bash
$ curl -X POST http://localhost:1024/make_thumbnail -H 'content-type: multipart/form-data; boundary=----Isthatallthereis' -F 'file=@/Users/ljaouen/Pictures/images-test/arbre.jpg'
{
   "ny_thumb": 86,
   "nx_thumb": 128,
   "mimetype_thumb": "image/jpeg",
   "preview_path": "http://iiif-local:1024/thumbs/Ajbg21Y02pi-FsknCEnndCb.jpg/full/full/0/default.jpg",
   "file_type": "IMAGE",
   "original_filename": "arbre.jpg",
   "original_mimetype": "image/jpeg",
   "filename": "Ajbg21Y02pi-FsknCEnndCb"
}
$ curl -X POST http://localhost:1024/make_thumbnail -H 'content-type: multipart/form-data; boundary=----Isthatallthereis' -F 'file=@/Users/ljaouen/Pictures/images-test/original.png'
{
   "message": "Submitted mimetypes and/or file extension are inconsistent"
}
```

:(

**Comment by lrosenth** [comment]
Je suis en train de regarder.... :-|

Lukas

Am 21.11.2018 um 10:03 schrieb Loïc Jaouen <notifications@github.com<mailto:notifications@github.com>>:


I couldn't make it work in server mode:

$ curl -X POST http://localhost:1024/make_thumbnail -H 'content-type: multipart/form-data; boundary=----Isthatallthereis' -F 'file=@/Users/ljaouen/Pictures/images-test/arbre.jpg'
{
   "ny_thumb": 86,
   "nx_thumb": 128,
   "mimetype_thumb": "image/jpeg",
   "preview_path": "http://iiif-local:1024/thumbs/Ajbg21Y02pi-FsknCEnndCb.jpg/full/full/0/default.jpg",
   "file_type": "IMAGE",
   "original_filename": "arbre.jpg",
   "original_mimetype": "image/jpeg",
   "filename": "Ajbg21Y02pi-FsknCEnndCb"
}
$ curl -X POST http://localhost:1024/make_thumbnail -H 'content-type: multipart/form-data; boundary=----Isthatallthereis' -F 'file=@/Users/ljaouen/Pictures/images-test/original.png'
{
   "message": "Submitted mimetypes and/or file extension are inconsistent"
}

:(

**Comment by loicjaouen** [comment]
@lrosenth merci de ton attention pour nos problèmes :)

l'image est la même que postée dans l'_issue_ d'origine:

https://user-images.githubusercontent.com/3933654/48060498-6df9f880-e1bc-11e8-9d00-d40d4f982e53.png

**Comment by lrosenth** [comment]
I think now the problem is in the lua script "make_thumbnail.lue".... It's not at the core of SIPI...



Am 21.11.2018 um 10:03 schrieb Loïc Jaouen <notifications@github.com<mailto:notifications@github.com>>:


I couldn't make it work in server mode:

$ curl -X POST http://localhost:1024/make_thumbnail -H 'content-type: multipart/form-data; boundary=----Isthatallthereis' -F 'file=@/Users/ljaouen/Pictures/images-test/arbre.jpg'
{
   "ny_thumb": 86,
   "nx_thumb": 128,
   "mimetype_thumb": "image/jpeg",
   "preview_path": "http://iiif-local:1024/thumbs/Ajbg21Y02pi-FsknCEnndCb.jpg/full/full/0/default.jpg",
   "file_type": "IMAGE",
   "original_filename": "arbre.jpg",
   "original_mimetype": "image/jpeg",
   "filename": "Ajbg21Y02pi-FsknCEnndCb"
}
$ curl -X POST http://localhost:1024/make_thumbnail -H 'content-type: multipart/form-data; boundary=----Isthatallthereis' -F 'file=@/Users/ljaouen/Pictures/images-test/original.png'
{
   "message": "Submitted mimetypes and/or file extension are inconsistent"
}

:(

**Comment by loicjaouen** [comment]
probably, let's close this and move it to knora then

**Pull request merged**
