### PR TITLE
J2kverify

### PR DESCRIPTION
**Pull request by lrosenth**
I changed completeley the error handling within the Lua functions that SIPI provides. Almost all are returning now to values:
```lua
success, value = a_sipi_lua_function()
if not success then
   process_error(value) -- value is error message in this case
end
-- value contains the "payload" that a_sipi_lua_function() returned
```

In addition a implemented my own logging class "Logger" which is a subclass of
ostream.
The usual tests seem to work...

@benjamingeer @tobiasschweizer @subotic Since the Sipi Lua-functions have changed, You will have to rework all Lua scripts. Those in the SIPI-tree have been rewritten be me (without testing!).
The only relevant change is described above!

### CODE REVIEW

**Comment by BiancoA** [comment]
Dear Lukas,

Thanks for the Pull request, in the next days I'll review it.

Bests,
Andrea

**Comment by BiancoA** [comment]
Dear Lukas,

Looking at the errors in linux, it seems that  `#include <memory>` is missing in SipiError.h, I keep looking around the code.

bests,
Andrea

**Comment by BiancoA** [comment]
Dear Lukas, 

It seems to me that the new Logger class is lacking a bit of documentation. Could you add something in the Logger.h file?

Bests,
Andrea

**Comment by lrosenth** [comment]
Done! Is now documented…

Regards,
	Lukas
--  

Prof. Dr. Lukas Rosenthaler
Head of "Digital Humanities Lab",
University of Basel
Bernoullistrasse 32
CH-4056 Basel, Switzerland

Tel: + 41 61 267 0490
Fax: +41 61 267 3855
http://www.dhlab.unibas.ch

**Comment by BiancoA** [comment]
Dear Lukas,

i added two other libraries include that where missing under linux. Travis for macos has now some problems, but it is not our fault. They say that they are having some issues with macos.

I compiles and works for me, I think you can merge it!
Bests 
Andrea

**Comment by tobiasschweizer** [comment]
I experience some problems with the Lua scripts.

**Pull request merged**
