### PR TITLE
Openssl

### PR DESCRIPTION
**Pull request by lrosenth**
Hi,
I added the OpenSSL support to SIPI, both for incoming as for outgoing connection.OpenSSL support requires that the OpenSSL library and development files are installed both on the deployment as well a compilation system. The location of the certificate files is given in the configuration file of SIPI. This SIPI can act as a https-server and – from Lua – make https requests.

cc: @subotic @tobiasschweizer

### CODE REVIEW

**Comment by BiancoA** [comment]
Dear Lukas,

Thanks for the pull request!
I will have a look at this changes when I am back on Monday.
Have a nice day,

Andrea

**Comment by lrosenth** [comment]
OK, now the openssl branch is ready. Let's merge :-)
@BiancoA @subotic @tobiasschweizer

**Comment by BiancoA** [comment]
Perfect! I will have a look at it on Monday. in the meanwhile I saw that travis is not able to compile it, it seems because the openssl-develop package is missing in the linux version, could you have a look at it @subotic ?

`/usr/src/sipi/lib/shttps/jwt.c:23:25: fatal error: openssl/bio.h: No such file or directory
`

i guess why it works on mac os... http://stackoverflow.com/questions/33165174/fatal-error-openssl-bio-h-file-not-found

**Comment by tobiasschweizer** [comment]
I had the same problem on my centos vm

installing openssl-devel and recompiling from scratch solved the problem

**Comment by BiancoA** [comment]
@lrosenth the build now fails at:

```
/Users/travis/build/dhlab-basel/Sipi/lib/shttps/LuaServer.cpp:52:10: fatal error: 'jansson.h' file not found
#include <jansson.h>
```

is some other library missing?

**Comment by BiancoA** [comment]
Ok, now it found jansson.h. But it still fails in the mac os x Build. Still openssl library is missing, it seems.

**Comment by tobiasschweizer** [comment]
Lukas wants the user to take care of an openssl installation on the system. It won't be included in the Makefile but it is dynamically linked.

**Comment by subotic** [comment]
The Travis build is now fixed. I have added the openssl library to the docker image.

**Comment by BiancoA** [comment]
now the compiling on travis works.

I checked visually the code and it seems OK. @tobiasschweizer can you test it with knora?

I will run some tests on my local linux machine for images conversion

**Comment by BiancoA** [comment]
@lrosenth I found some problems on my ubuntu machine:
I modified sipi.config.lua adding `    imgroot = './test_server/images',` , and, after running sipi,

using a web browser, if I try to access:

 

- `http://localhost:1024/test_server/Leaves8.tif/full/full/0/default.jp2` . Sipi **crashes** and gdb says:

```
(gdb) run -config config/sipi.config.lua
Starting program: /home/andrea/Src/github/Sipi/local/bin/sipi -config config/sipi.config.lua
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Sipi Version 1.0 Beta (build 2016-07-18 15:12)
[New Thread 0x7ffff2d6e700 (LWP 14526)]
[New Thread 0x7ffff256d700 (LWP 14528)]
Error in Kakadu File Format Support:
You cannot use `jp2_output_box::write_header_last' unless this is a top level
box and the underlying `jp2_family_tgt' object represents a file.
[Thread 0x7ffff256d700 (LWP 14528) exited]
[Thread 0x7ffff7fc7780 (LWP 14522) exited]
[Inferior 1 (process 14522) exited with code 0377]


```
-  `http://localhost:1024/test_server/Leaves8.tif/full/full/0/default.jpg` _it works_,
-  `http://localhost:1024/test_server/Leaves8.tif/full/full/0/default.png` _it works_,
- `http://localhost:1024/test_server/Leaves8.tif/full/full/0/default.tif` _it works_.

- ` http://localhost:1024/test_server/Leaves.jpg/full/full/0/default.png` sipi goes in **segmentation fault**. 
- ` http://localhost:1024/test_server/Leaves.jpg/full/full/0/default.jpg` _it works_.
-` http://localhost:1024/test_server/Leaves.jpg/full/full/0/default.jp2` **it crashes** as in the case with the tif image.
- ` http://localhost:1024/test_server/Leaves.jpg/full/full/0/default.tif` **it crashes**: 
```
Sipi Version 1.0 Beta (build 2016-07-18 15:12)
sipi: /home/andrea/Src/github/Sipi/lib/libtiff-4.0.6/libtiff/tif_dirwrite.c:2335: TIFFWriteDirectoryTagData: Assertion `datalength<0x80000000UL' failed.
Aborted (core dumped)

```

**Comment by subotic** [comment]
Isn't it time to write some tests? I see that there is a lot of testing-by-hand going on, and subsequently a lot of time wasted, as these tests could be automated. Also, these kind of errors shouldn't even creep in, as they could have been found out by simply running a few tests.

How are we suppose to maintain a high quality product if no tests are present?

**Comment by lrosenth** [comment]
I'll have a look. Its a JSON-Library... i have the computer with me....

Best reagards,
Lukas

Sent from my iPad

On 18.07.2016, at 11:01, Andrea Bianco <notifications@github.com<mailto:notifications@github.com>> wrote:


@lrosenth<https://github.com/lrosenth> the build now fails at:

/Users/travis/build/dhlab-basel/Sipi/lib/shttps/LuaServer.cpp:52:10: fatal error: 'jansson.h' file not found
#include <jansson.h>


is some other library missing?

**Comment by lrosenth** [comment]
You have to install openssl by hand (using homebrew)...

Sent from my iPad

On 18.07.2016, at 11:18, Andrea Bianco <notifications@github.com<mailto:notifications@github.com>> wrote:


Ok, now it found jansson.h. But it still fails in the mac os x Build. Still openssl library is missing, it seems.

**Comment by lrosenth** [comment]
@BiancoA Hi Andrea, Do You have time to have a look at the openssl branch. I would like to merge it...

**Comment by BiancoA** [comment]
Hi Lukas,

Tomorrow morning I'll check the openssl branch, next time we meet we should also discuss this point raised by Benjamin https://github.com/dhlab-basel/Sipi/issues/43 aka Sourceforge not always responding.

**Comment by lrosenth** [comment]
Hi Andrea,

that’s perfect. Yes, sourcefourge seems to be a problem. I suggest to create ASAP a SIPI webseite, where all the third-party software is ready to download… I beleive on the long run this is a better solution…

Greetings from the beach,
	Lukas
--  

Prof. Dr. Lukas Rosenthaler
Head of "Digital Humanities Lab",
University of Basel
Bernoullistrasse 32
CH-4056 Basel, Switzerland

Tel: + 41 61 267 0490
Fax: +41 61 267 3855
http://www.dhlab.unibas.ch

**Comment by BiancoA** [comment]
Dear Lukas,

I still see some problems converting tif file 16 bit to jpeg and png, and tif file to jp2. To automate a bit the test phase, I added a new image in `test_server/images` that is a tif 16 bit. 

I also wrote 3 scripts in bash, that will be expanded in future, to speed up the testing. To use them launch sipi with the config file `sipi.test-config.lua` and, in another terminal, move to the folder `test_server/`. From there you can launch each script, with as an argument, the PID that was assigned to sipi by the operating system (`ps -C sipi`), for example like this:

```
bash test_png.sh 11236
```

where 11236 is the PID for this session of sipi, and look at the results.

**Comment by lrosenth** [comment]
Hi Andrea,

I'll have a look at it...

Lukas

Von meinem iPhone gesendet

Am 28.07.2016 um 14:46 schrieb Andrea Bianco <notifications@github.com<mailto:notifications@github.com>>:


Dear Lukas,

I still see some problems converting tif file 16 bit to jpeg and png, and tif file to jp2. To automate a bit the test phase, I added a new image in test_server/images that is a tif 16 bit.

I also wrote 3 scripts in bash, that will be expanded in future, to speed up the testing. To use them launch sipi with the config file sipi.test-config.lua and, in another terminal, move to the folder test_server/. From there you can launch each script, with as an argument, the PID that was assigned to sipi by the operating system (ps -C sipi), for example like this:

bash test_png.sh 11236


where 11236 is the PID for this session of sipi, and look at the results.

**Comment by lrosenth** [comment]
Hi Andrea,

I’m currently on the ferry between Calvi (Corsica) and Nice. I tried the test scripts You indicated below. At least on my mac everything works finde, even with the new image. We have to look on Ubuntu where the problem lies…

Best Regards from our way back home…

Lukas

--  

Prof. Dr. Lukas Rosenthaler
Head of "Digital Humanities Lab",
University of Basel
Bernoullistrasse 32
CH-4056 Basel, Switzerland

Tel: + 41 61 267 0490
Fax: +41 61 267 3855
http://www.dhlab.unibas.ch

**Comment by BiancoA** [comment]
Dear Lukas,

I will be back in the Lab on Wednesday, we can have a look together then.

Have a nice coming back home.

Andrea

**Pull request merged**
