### PR TITLE
build (travis): fix for travis stages

### PR DESCRIPTION
**Pull request by subotic**
Fixes (I hope) the current Travis publish stage failure.

### CODE REVIEW

**Comment by subotic** [comment]
@benjamingeer this should be a fast review :-)

**Comment by subotic** [comment]
Thanks :-)

**Comment by subotic** [comment]
Sourceforge is so frustrating:

```
[ 11%] Performing download step (download, verify and extract) for 'project_xz'
-- File already exists but no hash specified (use URL_HASH):
  file='/sipi/build/ext/xz/project_xz-prefix/src/xz-5.2.1.tar.gz'
Old file will be removed and new file downloaded from URL.
-- Downloading...
   dst='/sipi/build/ext/xz/project_xz-prefix/src/xz-5.2.1.tar.gz'
   timeout='none'
-- Using src='http://sourceforge.net/projects/lzmautils/files/xz-5.2.1.tar.gz/download'
-- [download 100% complete]
-- Downloading... done
-- extracting...
     src='/sipi/build/ext/xz/project_xz-prefix/src/xz-5.2.1.tar.gz'
     dst='/sipi/extsrcs/xz-5.2.1'
-- extracting... [tar xfz]
CMake Error: Problem with archive_read_open_file(): Unrecognized archive format
CMake Error: Problem extracting tar: /sipi/build/ext/xz/project_xz-prefix/src/xz-5.2.1.tar.gz
CMake Error at /sipi/build/ext/xz/project_xz-prefix/src/project_xz-stamp/extract-project_xz.cmake:33 (message):
  error: extract of
  '/sipi/build/ext/xz/project_xz-prefix/src/xz-5.2.1.tar.gz' failed
-- extracting... [error clean up]
```

It happened last night the whole time. Then this morning the build passed, and now it fails again with the same error.

**Comment by subotic** [comment]
lol, googling for `Sourceforge CMake Error: Problem with archive_read_open_file(): Unrecognized archive format` returned [this](https://www.google.ch/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwj61I2-scvZAhVOrRQKHQwaDBwQFggpMAA&url=https%3A%2F%2Fgithub.com%2Fdhlab-basel%2FSipi%2Fissues%2F43&usg=AOvVaw0YuVN8JhZ-my_MzSWAb3hj) as the first hit.

**Comment by benjamingeer** [comment]
Maybe it's time to reopen that issue. :)

**Comment by subotic** [comment]
We have an open issue: https://github.com/dhlab-basel/Sipi/issues/142

**Comment by subotic** [comment]
but we have so many of them ;-)

**Comment by subotic** [comment]
Moving files gradually to [bintray](https://bintray.com/dhlab-basel/thirdparty). Sourceforge is having an exceptionally bad day.

**Comment by subotic** [comment]
finally, the build goes through.

**Pull request merged**
