### PR TITLE
Luahttpget

### PR DESCRIPTION
**Pull request by lrosenth**
I added a HTTP client to the SIPI lua-interpreter. It's called by
```
server.http("GET", "http:/www.salsah.org/api/resources/2")
```
cc: @tobiasschweizer @benjamingeer

### CODE REVIEW

**Comment by BiancoA** [comment]
Dear Lukas,

thanks for the pull request. If I understand correctly we only support ipv4 addresses `shttps/Server.cpp` line 505 is `char client_ip[20]; `. Maybe we should write it somewhere, or we can consider it as implied...

I think you can merge.

**Comment by lrosenth** [comment]
Hi Andrea,

yes, we should state it in the readme and extend on occasion the code in order to support also IP6 :-)

Thanks,
	Lukas

P.S. Just tell me, when i can merge it…

--  

Prof. Dr. Lukas Rosenthaler
Head of "Digital Humanities Lab",
University of Basel
Bernoullistrasse 32
CH-4056 Basel, Switzerland

Tel: + 41 61 267 0490
Fax: +41 61 267 3855
http://www.dhlab.unibas.ch

**Comment by BiancoA** [comment]
I think you can merge it right now!

Bests,
Andrea

**Comment by lrosenth** [comment]
I added IP4 and IP6 support and added the client-IP and client-port to the LUA server table as "server.client_ip" and "server.client_port". Thus, the preflight script is able to check the IP and can use the client IP address for a decision about permissions (e.g. opening a whole range of IP's for unrestricted access, e.g. all 131.152.*. This checking would have to be done inside LUA.

**Comment by BiancoA** [comment]
Dear Lukas, 

Tomorrow I will check the pull request, since today I am working from home. But I see that the build steps for travis failed (it seems that sourgeforce was not responding). I checked the url and now it should work. @subotic could you re-start the travis building process? the re-start button does not appear to me.

Bests

**Comment by BiancoA** [comment]
@subotic my bad. I was not logged in travis. Silly problem solved. Thanks anyway!

**Comment by BiancoA** [comment]
Dear Lukas,

I think you can merge luahttpget branch.

Think again,
Have a nice day
Andrea

**Comment by lrosenth** [comment]
OK, I merged and pushed it...

**Pull request closed without merging**
