### PR TITLE
Wip/gray img bug

### PR DESCRIPTION
**Pull request by lrosenth**
@tobiasschweizer Please have a look. Implemented

1) Support of palette color TIFFS

2) kakadu v7_A_2

Pleadse note that You have to copy v7_A_2 from the Dropbox to the vendor directory in SIPI

### CODE REVIEW

**Comment by tobiasschweizer** [comment]
@subotic The build fails on travis because a new Kakadu version is required, but it is not available to travis:

> unzip:  cannot find or open /sipi/vendor/v7_A_2-01382N.zip

Could you update the Kakadu zip? Thanks!

**Comment by subotic** [comment]
yes, will do it right away.

**Comment by tobiasschweizer** [comment]
I had to update `imagemagick` to version 7.0.7-8 (with `brew` on my Mac) 

However, I still have a problem with `iiid_validator`. When I run it, I get:

```
E           conftest.SipiTestError: IIIF validation failed (wrote /Users/tobi/gitreps/Sipi/test/e2e/sipi.log):
E           Traceback (most recent call last):
E             File "/usr/local/lib/python3.6/site-packages/iiif_validator/validator.py", line 22, in <module>
E               from PIL import Image, ImageDraw
E             File "/usr/local/lib/python3.6/site-packages/PIL/Image.py", line 67, in <module>
E               from PIL import _imaging as core
E           ImportError: dlopen(/usr/local/lib/python3.6/site-packages/PIL/_imaging.cpython-36m-darwin.so, 2): Library not loaded: /usr/local/opt/jpeg/lib/libjpeg.8.dylib
E             Referenced from: /usr/local/lib/python3.6/site-packages/PIL/_imaging.cpython-36m-darwin.so
E             Reason: image not found
E           
E           During handling of the above exception, another exception occurred:
E           
E           Traceback (most recent call last):
E             File "/usr/local/bin/iiif-validate.py", line 11, in <module>
E               from iiif_validator.validator import ValidationInfo,TestSuite,ImageAPI
E             File "/usr/local/lib/python3.6/site-packages/iiif_validator/validator.py", line 24, in <module>
E               import Image, ImageDraw
E           ModuleNotFoundError: No module named 'Image'
```

This is not related to Sipi at all.

**Comment by tobiasschweizer** [comment]
Thank you, Ivan!

**Comment by tobiasschweizer** [comment]
Pillow has to be upgraded:

`pip3 install --upgrade pillow`

**Comment by tobiasschweizer** [comment]
@lrosenth Ok, I ran the tests and also did some heavy extra load testing for IIIF regions and it works fine!

However, I do not understand the changes you introduced in `src/formats/SipiIOTiff.cpp` and `src/metadata/SipiIcc.cpp`. Could you explain them to me?

**Pull request merged**
