### PR TITLE
Jpegbug

### PR DESCRIPTION
**Pull request by lrosenth**
It should work now better. Made some stress-tests with 630 different JPEG's and J2K's loading in a JavaScript loop. No more error or problem (even if the cache has been disabled)...

### CODE REVIEW

**Comment by BiancoA** [comment]
@lrosenth I am testing Sipi, but it seems that the program quits as soon as it is started. Is it working on mac?

**Comment by BiancoA** [comment]
@lrosenth My bad, I already had a sipi running on my machine. It passed all the tests, I think you can merge it!

**Comment by lrosenth** [comment]
Hi,

I'm working on better error recovery :-). Which doesn't right now as expected :-(

Keep You informed...

Sent from my iPad

On 3 Nov 2016, at 10:13, Andrea Bianco <notifications@github.com<mailto:notifications@github.com>> wrote:


@lrosenth<https://github.com/lrosenth> My bad, I already had a sipi running on my machine. It passed all the tests, I think you can merge it!

**Comment by BiancoA** [comment]
I tested it on ubuntu 16.04. Everything works. If you can check on the other linux virtual machines, it would be perfect. You can merge it.

**Comment by lrosenth** [comment]
Merged...

**Pull request closed without merging**
