### PR TITLE
fix: knora upload scripts and configs

### PR DESCRIPTION
**Pull request by lrosenth**
### Summary

 - update Knora scripts to work with new `subdir_levels` feature
 - add `subdir_exludes` list with directories which should be skipped by sipi 
 - rename `wwwroute` in config files
 - add better error output in LuaServer now containing the name of the script failing

### CODE REVIEW

**Comment by subotic** [comment]
There is still something not right, or at least something about the automatically generated sub-directories that I don't understand.

**Comment by subotic** [comment]
@benjamingeer I was part of the PR so maybe you should do the review.

**Comment by benjamingeer** [comment]
OK but I don't know what this is for, please write a description for the PR explaining what was changed.

**Comment by subotic** [comment]
I've added a summary in the description. Thanks.

**Comment by benjamingeer** [comment]
Now that there's a working test framework, could you add a test for this feature? I think it would be good to have a test of the feature that automatically restructures existing files into subdirectories when the Sipi server starts. Especially if there are a large number of existing files.

**Comment by subotic** [comment]
Gladly, if it is ok to create an issue for this and do it in another PR? I need this pull request merged so that I can merge https://github.com/dhlab-basel/Knora/pull/534.

Also, need to work on another pile more urgently ;-)

**Comment by subotic** [comment]
Created issue #177

**Comment by benjamingeer** [comment]
OK!

**Comment by subotic** [comment]
Thanks :-)

**Pull request merged**
