### PR TITLE
fix (scripts): add better error output and type transformation

### LINKED ISSUE #161: Call to Sipi failed when trying to upload a .TIF
Some images in .TIF from a research project cannot apparently be uploaded in Salsah by Sipi. I am not really confident regarding the data quality, formats, etc.

However, even though I got a "call to Sipi failed" error, I can open the file in Photoshop without problem. And when I save it as another file (the filename is not an issue), Sipi is then able to upload it.

Do you want me to provide you with those 2 images (34Mo each)?

### PR DESCRIPTION
**Pull request by subotic**
### Summary

- add better error output
- add transformation to string in error output
- tiff upload problem: resolves #161

### CODE REVIEW

**Comment by lrosenth** [comment]
Can You resolve the conflicts @subotic

**Comment by subotic** [comment]
conflict is fixed.

**Comment by subotic** [comment]
As I understand it, this is fixed in PR #198 ?

**Comment by subotic** [comment]
merged the `wip/fix-scripts` branch into the `fragmentarium` branch and will close this PR.

**Pull request closed without merging**
